### ISSUE TITLE
Wrong base address for models

### ISSUE THREAD

**Issue by Nedi11** [nielsbasjes/energy#299]
I am testing this out on a Fimer PVS inverter. After running the example in the docs I get this error:
![image](https://github.com/nielsbasjes/energy/assets/91092824/1f409c2f-26fc-4b81-a226-c57cb1dbb2fe)

The result of `getAllModels() `:

`{1=ModelLocation{id=1, registerBase=40004, len=66}, 103=ModelLocation{id=103, registerBase=40072, len=50}, 120=ModelLocation{id=120, registerBase=40124, len=26}, 121=ModelLocation{id=121, registerBase=40152, len=30}, 122=ModelLocation{id=122, registerBase=40184, len=44}, 123=ModelLocation{id=123, registerBase=40230, len=24}, 126=ModelLocation{id=126, registerBase=40256, len=226}, 127=ModelLocation{id=127, registerBase=40484, len=10}, 129=ModelLocation{id=129, registerBase=40496, len=60}, 130=ModelLocation{id=130, registerBase=40558, len=60}, 132=ModelLocation{id=132, registerBase=40620, len=226}, 135=ModelLocation{id=135, registerBase=40848, len=60}, 136=ModelLocation{id=136, registerBase=40910, len=60}, 139=ModelLocation{id=139, registerBase=40972, len=60}, 140=ModelLocation{id=140, registerBase=41034, len=60}, 145=ModelLocation{id=145, registerBase=41096, len=8}, 160=ModelLocation{id=160, registerBase=41106, len=248}, 65230=ModelLocation{id=65230, registerBase=41356, len=1}, 65232=ModelLocation{id=65232, registerBase=41359, len=20}}
`

First model register base shows as 40004 but if I use a modbus reader you can see that the first 2 registers are at 40000 and 40001. Id of the first model is at 40003 and length at 40004.
![image](https://github.com/nielsbasjes/energy/assets/91092824/48b63a84-af56-4d6a-a68e-3fa997f4b825)

Unless you mean register base to be the length register

**Comment by nielsbasjes** [comment]
For the first point; do you have the commons-lang3 dependency loaded?

The other is a notorious problem with modbus is that the modicon standard notation has an "off by 1" as part of the standard. It gets really confusing very quickly because there is little concesus on how to write it all.

So it is very likely I have made a mistake in this area.
I am working on a complete rewrite of all of this because of all of this.

**Comment by Nedi11** [comment]
Adding commons-lang3 dependency fixed the first issue. 
The register values also seem to be correct when I compare them with the values from the Modbus reader.
I tested model 103 and compared the first 2 values, Amps and AmpsPhaseA.
